// UPC → W3C PROV-O export (crosswalks/prov.md).
//
// A deterministic, zero-dependency projection of a UPC corpus into flattened
// PROV-O JSON-LD. Export only: the UPC objects remain canonical; this is a
// regenerable view like index.html / ro-crate-metadata.json. No JSON-LD
// processor and no network are needed to emit it — a consumer that wants RDF
// runs its own processor against the referenced @context.
//
// It records DERIVATION, not verification. The hop-B/C quotation gate is
// UPC-only and is NOT carried here: a plain PROV consumer cannot re-run it (§11).
// Per crosswalks/prov.md we deliberately:
//   * never emit prov:hadPrimarySource (a UPC source is a captured resource, not
//     a claimed primary source);
//   * map supersedes/superseded_by — NOT a representation's duplicate_of — to
//     prov:wasRevisionOf;
//   * emit prov:wasQuotedFrom for direct_quote extractions while carrying none of
//     the gate's mechanical guarantee.
//
// Determinism: @graph and every ref array are sorted by @id, key order is fixed,
// and no wall-clock / random is used (timestamps come only from stored events).

import * as U from "./upc_common.mjs";

const PROV = "http://www.w3.org/ns/prov#";
const XSD = "http://www.w3.org/2001/XMLSchema#";
const UPC_TERMS = "https://provenance.dev/upc/terms#";

const byId = (a, b) => (a["@id"] < b["@id"] ? -1 : a["@id"] > b["@id"] ? 1 : 0);
const sortRefs = (arr) => arr.slice().sort(byId);
const uniqRefs = (arr) => {
  const seen = new Set();
  const out = [];
  for (const r of arr) if (r && !seen.has(r["@id"])) { seen.add(r["@id"]); out.push(r); }
  return out;
};

/**
 * Build the PROV-O graph object from a loaded corpus (U.loadCorpus result).
 * Pure: no IO, no clock, no random. Every UPC object is a prov:Entity, every
 * event a prov:Activity, and each tool/person a prov:Agent.
 */
export function buildProvGraph(loaded) {
  const ref = (id) => (id ? { "@id": "#" + id } : null);
  // Flatten a grouped-by-kind bucket (derived_from / inputs / outputs) to sorted refs.
  const bucketRefs = (grp) => {
    if (!grp) return [];
    const ids = [];
    for (const arr of Object.values(grp)) for (const id of arr || []) ids.push(id);
    return sortRefs(uniqRefs(ids.map(ref).filter(Boolean)));
  };

  const nodes = [];
  const tools = new Map();   // "#tool-slug" -> agent node
  const persons = new Map(); // "#person-slug" -> agent node

  // Tool + person agents for a produced_by-like object; returns [ref, ...] (tool then person).
  const agentRefs = (pb) => {
    const refs = [];
    if (pb && pb.tool) {
      const id = "#tool-" + U.slugify(pb.tool + (pb.tool_version ? "-" + pb.tool_version : ""));
      if (!tools.has(id)) {
        const a = { "@id": id, "@type": ["prov:Agent", "prov:SoftwareAgent"], "upc:name": pb.tool };
        if (pb.tool_version) a["upc:version"] = pb.tool_version;
        tools.set(id, a);
      }
      refs.push({ "@id": id });
    }
    if (pb && pb.person) {
      const id = "#person-" + U.slugify(pb.person);
      if (!persons.has(id)) persons.set(id, { "@id": id, "@type": ["prov:Agent", "prov:Person"], "upc:name": pb.person });
      refs.push({ "@id": id });
    }
    return refs;
  };
  const attachAgents = (e, pb) => {
    const refs = agentRefs(pb);
    if (refs.length) e["prov:wasAttributedTo"] = refs;
  };

  // Output entity id -> producing activity id. Deterministic: first event that
  // lists the entity as an output, by sorted event_id (an entity generated by
  // more than one event keeps a single, stable wasGeneratedBy).
  const genBy = new Map();
  const eventsSorted = loaded.events.slice().sort((a, b) => (String(a.event_id) < String(b.event_id) ? -1 : 1));
  for (const ev of eventsSorted) {
    for (const arr of Object.values(ev.outputs || {})) for (const id of arr || []) {
      if (id && !genBy.has(id)) genBy.set(id, ev.event_id);
    }
  }
  const generatedBy = (id) => (genBy.has(id) ? { "@id": "#" + genBy.get(id) } : null);

  // --- Sources: roots. wasGeneratedBy the fetch activity; NEVER hadPrimarySource. ---
  for (const s of loaded.sources) {
    if (!s.obj) continue;
    const o = s.obj, pv = o.provenance || {};
    const e = { "@id": "#" + o.source_id, "@type": "prov:Entity", "upc:kind": "source" };
    const g = generatedBy(o.source_id); if (g) e["prov:wasGeneratedBy"] = g;
    attachAgents(e, pv.produced_by);
    if (o.supersedes) e["prov:wasRevisionOf"] = ref(o.supersedes);
    nodes.push(e);
  }

  // --- Representations: derived from their parent representation, else their source. ---
  for (const r of loaded.representations) {
    const o = r.obj, pv = o.provenance || {};
    const e = { "@id": "#" + o.representation_id, "@type": "prov:Entity", "upc:kind": "representation" };
    const from = o.parent_representation_ref || r.sourceId;
    if (from) e["prov:wasDerivedFrom"] = [ref(from)];
    const g = generatedBy(o.representation_id); if (g) e["prov:wasGeneratedBy"] = g;
    attachAgents(e, pv.produced_by);
    // duplicate_of is intentionally NOT mapped to wasRevisionOf (a duplicate is not a revision).
    nodes.push(e);
  }

  // --- Extractions: derived from their representation; wasQuotedFrom for direct quotes. ---
  for (const x of loaded.extractions) {
    const o = x.obj, pv = o.provenance || {};
    const e = { "@id": "#" + o.extraction_id, "@type": "prov:Entity", "upc:kind": "extraction" };
    if (o.representation_ref) e["prov:wasDerivedFrom"] = [ref(o.representation_ref)];
    const active = (o.status || "active") === "active";
    if (active && o.direct_quote != null && o.representation_ref) {
      // Records where the quotation came from. Carries NONE of the hop-B gate guarantee.
      e["prov:wasQuotedFrom"] = ref(o.representation_ref);
    }
    const g = generatedBy(o.extraction_id); if (g) e["prov:wasGeneratedBy"] = g;
    attachAgents(e, pv.produced_by);
    if (o.supersedes) e["prov:wasRevisionOf"] = ref(o.supersedes);
    nodes.push(e);
  }

  // --- Generations & Syntheses: derived from provenance.derived_from. ---
  const derivedObj = (id, kind, o) => {
    const pv = o.provenance || {};
    const e = { "@id": "#" + id, "@type": "prov:Entity", "upc:kind": kind };
    const df = bucketRefs(pv.derived_from);
    if (df.length) e["prov:wasDerivedFrom"] = df;
    if (pv.activity_ref) e["prov:wasGeneratedBy"] = ref(pv.activity_ref);
    else { const g = generatedBy(id); if (g) e["prov:wasGeneratedBy"] = g; }
    attachAgents(e, pv.produced_by);
    if (pv.produced_by && pv.produced_by.model) e["upc:model"] = pv.produced_by.model;
    return e;
  };
  for (const g of loaded.generations) nodes.push(derivedObj(g.obj.generation_id, "generation", g.obj));
  for (const y of loaded.syntheses) nodes.push(derivedObj(y.obj.synthesis_id, "synthesis", y.obj));

  // --- Activities: one prov:Activity per journal event. ---
  for (const ev of loaded.events) {
    const e = { "@id": "#" + ev.event_id, "@type": "prov:Activity", "upc:activityType": ev.activity_type };
    if (ev.started_at) e["prov:startedAtTime"] = ev.started_at;
    if (ev.ended_at) e["prov:endedAtTime"] = ev.ended_at;
    const used = bucketRefs(ev.inputs); if (used.length) e["prov:used"] = used;
    const assoc = agentRefs({ tool: ev.tool, tool_version: ev.tool_version, person: ev.person });
    if (assoc.length) e["prov:wasAssociatedWith"] = assoc;
    if (ev.model) e["upc:model"] = ev.model;
    nodes.push(e);
  }

  const graph = nodes
    .concat(Array.from(tools.values()), Array.from(persons.values()))
    .sort(byId);

  return {
    "@context": {
      prov: PROV,
      xsd: XSD,
      upc: UPC_TERMS,
      "prov:startedAtTime": { "@type": "xsd:dateTime" },
      "prov:endedAtTime": { "@type": "xsd:dateTime" },
    },
    "@graph": graph,
  };
}
